import Head from "next/head"
import { useRouter } from "next/router"
import { Accounts } from "~/components/Global"
import { getDirectoryAccounts } from "~/slices/accountsSlice"

export default function Directory() {
   const router = useRouter()
   const id = router!.query!.directoryId as string 
   
   return (
      <Accounts 
         dispatchFunction={() => getDirectoryAccounts(id)} 
         prefix="favorites"
         in_directory={id}
      >
         <Head>
            <title>Directory</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
      </Accounts>
   )
}