import Head from "next/head"
import { Inter } from "@next/font/google"
import Sidenav from "~/components/Global/Sidenav"
import { useAppDispatch, useAppSelector } from "~/redux/hooks"
import { incrementTimer } from "~/slices/authSlice"
import { useEffect } from "react"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
   const dispatch = useAppDispatch()
   const {time_left} = useAppSelector(state => state.auth)
   useEffect(() =>{
      setInterval(() => {
         // dispatch(incrementTimer())
      }, 1000)
   },[])
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         {time_left.minutes}
         {time_left.seconds}
         <Sidenav />
      </>
   )
}
