import Head from "next/head"
import { useEffect, useState } from "react"
import { Protected } from "~/components/Global/Protected"
import Sidenav from "~/components/Global/Sidenav"
import { useAppDispatch, useAppSelector } from "~/redux/hooks"
import { fetchPasswords } from "~/slices/passwordsSlice"

export default function Home() {
   const dispatch = useAppDispatch()
   const {passwords} = useAppSelector(state => state.passwords)  
   const [loaded, setLoaded] = useState(false)

   useEffect(() => {
      (async () =>{
         await dispatch(fetchPasswords())
         setLoaded(true)
      })()
   },[])

   if(!loaded){
      return null
   }

   return (
      <Protected>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Sidenav />
      </Protected>
   )
}