import Head from "next/head"
import { Accounts } from "~/components/Global"
import { fetchFavoriteAccounts } from "~/slices/accountsSlice"

export default function Favorites() {
   return (
      <Accounts 
         dispatchFunction={fetchFavoriteAccounts} 
         prefix="favorites"
      >
         <Head>
            <title>Favorites</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
      </Accounts>
   )
}